import type { JobApplication } from "@/lib/types"

export const mockApplications: JobApplication[] = [
  {
    id: "1",
    jobId: "1",
    userId: "3",
    resumeUrl: "/resumes/resume1.pdf",
    answers: [
      {
        questionId: "q1",
        answer: "I have 5 years of experience with React and 3 years with Next.js",
      },
      {
        questionId: "q2",
        answer: "Yes",
      },
    ],
    status: "pending",
    appliedAt: "2024-02-25",
    updatedAt: "2024-02-25",
    job: {
      id: "1",
      title: "Senior Frontend Developer",
      company: "TechCorp Inc.",
      location: "San Francisco, CA",
      type: "Full-time",
      salary: "$120,000 - $160,000",
      description: "We are seeking a Senior Frontend Developer to join our team...",
      requirements: [
        "5+ years of experience with React",
        "Strong TypeScript skills",
        "Experience with Next.js",
        "Understanding of web performance optimization",
      ],
      responsibilities: [
        "Lead frontend development initiatives",
        "Mentor junior developers",
        "Architect scalable solutions",
        "Collaborate with design team",
      ],
      benefits: [
        "Competitive salary",
        "Health insurance",
        "401(k) matching",
        "Remote work options",
        "Professional development budget",
      ],
      postedAt: "2024-02-20",
      companyId: "1",
      applicationQuestions: [],
    },
  },
  {
    id: "2",
    jobId: "2",
    userId: "3",
    resumeUrl: "/resumes/resume1.pdf",
    answers: [],
    status: "reviewing",
    appliedAt: "2024-02-24",
    updatedAt: "2024-02-26",
    job: {
      id: "2",
      title: "UX Designer",
      company: "DesignPro",
      location: "New York, NY",
      type: "Full-time",
      salary: "$90,000 - $120,000",
      description: "Join our creative team as a UX Designer...",
      requirements: [
        "3+ years of UX design experience",
        "Proficiency in Figma",
        "Strong portfolio",
        "Experience with user research",
      ],
      responsibilities: [
        "Create user-centered designs",
        "Conduct user research",
        "Develop prototypes",
        "Collaborate with developers",
      ],
      benefits: ["Competitive salary", "Health benefits", "Flexible hours", "Design conference budget"],
      postedAt: "2024-02-21",
      companyId: "2",
      applicationQuestions: [],
    },
  },
  {
    id: "3",
    jobId: "3",
    userId: "3",
    resumeUrl: "/resumes/resume1.pdf",
    answers: [],
    status: "interview",
    appliedAt: "2024-02-22",
    updatedAt: "2024-02-28",
    interviewDate: "2024-03-05",
    interviewTime: "10:00 AM",
    interviewType: "Video",
    job: {
      id: "3",
      title: "Data Analyst",
      company: "DataTech",
      location: "Chicago, IL",
      type: "Full-time",
      salary: "$70,000 - $90,000",
      description: "Join our data team as a Data Analyst...",
      requirements: [
        "2+ years of data analysis experience",
        "Proficiency in SQL and Python",
        "Experience with data visualization tools",
        "Strong analytical skills",
      ],
      responsibilities: [
        "Analyze complex datasets",
        "Create insightful reports",
        "Identify trends and patterns",
        "Collaborate with stakeholders",
      ],
      benefits: ["Competitive salary", "Health benefits", "Flexible hours", "Professional development"],
      postedAt: "2024-02-20",
      companyId: "3",
      applicationQuestions: [],
    },
  },
]
