# Generated by Django 5.2.1 on 2025-05-10 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('applications', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employermetrics',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplicationmetrics',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='applications.application'),
        ),
        migrations.AddField(
            model_name='jobapplicationmetrics',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_metrics', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobview',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_views', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobview',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='employermetrics',
            index=models.Index(fields=['employer', 'created_at'], name='analytics_e_employe_6d9e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplicationmetrics',
            index=models.Index(fields=['job', 'status'], name='analytics_j_job_id_bab90f_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplicationmetrics',
            index=models.Index(fields=['created_at'], name='analytics_j_created_838b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='jobview',
            index=models.Index(fields=['job', 'viewed_at'], name='analytics_j_job_id_48fac2_idx'),
        ),
        migrations.AddIndex(
            model_name='jobview',
            index=models.Index(fields=['ip_address', 'viewed_at'], name='analytics_j_ip_addr_417dd6_idx'),
        ),
    ]
