# Generated by Django 5.2 on 2025-04-14 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_created_by_job_is_active_alter_job_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='applications',
            new_name='application_count',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='views',
            new_name='view_count',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
