# Generated by Django 5.2.1 on 2025-05-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.CharField(blank=True, choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail'), ('marketing', 'Marketing'), ('media', 'Media & Entertainment'), ('construction', 'Construction'), ('transportation', 'Transportation'), ('energy', 'Energy'), ('telecommunications', 'Telecommunications'), ('other', 'Other')], max_length=255, null=True),
        ),
    ]
