# Generated by Django 5.2.1 on 2025-05-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='achievements',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
