# Generated by Django 5.2.1 on 2025-05-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='company_name',
        ),
    ]
