# Generated by Django 5.2.1 on 2025-05-10 15:07

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, storage=core.storage.PublicAssetStorage(), upload_to='avatars/'),
        ),
    ]
