# Generated by Django 5.2 on 2025-04-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_campusprofile_employerprofile_studentprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
