# Generated by Django 5.2 on 2025-04-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
