# Generated by Django 5.2 on 2025-04-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_company_id'),
        ('users', '0007_resume'),
    ]

    operations = [
    ]
