# Generated by Django 5.2 on 2025-04-15 07:49

import users.models
import users.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_0005_customuser_company_id_0007_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='university',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(storage=users.storage.ResumeStorage(), upload_to=users.models.upload_to_student_directory),
        ),
    ]
