# Generated by Django 5.2.1 on 2025-05-09 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_description_alter_company_location'),
        ('users', '0009_alter_customuser_company_alter_customuser_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_profiles', to='companies.company'),
        ),
    ]
