# Generated by Django 5.2.1 on 2025-05-09 21:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Guide', 'Guide'), ('Video Course', 'Video Course'), ('Webinar', 'Webinar'), ('E-book', 'E-book'), ('Article', 'Article'), ('Workshop', 'Workshop')], max_length=50)),
                ('content', models.TextField(blank=True)),
                ('author', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_time', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('is_demo', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('downloads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='resources/')),
                ('file_type', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='resources.resource')),
            ],
        ),
    ]
