# Generated by Django 5.2.1 on 2025-05-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_complete',
            field=models.BooleanField(default=False),
        ),
    ]
