# Generated by Django 5.2.1 on 2025-05-10 15:23

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(max_length=255)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('founded', models.CharField(blank=True, max_length=4, null=True)),
                ('logo', models.ImageField(blank=True, null=True, storage=core.storage.PublicAssetStorage(), upload_to='company_logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, storage=core.storage.PublicAssetStorage(), upload_to='company_cover_images/')),
                ('verified', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('culture', models.TextField(blank=True, null=True)),
                ('benefits', models.JSONField(blank=True, null=True)),
                ('highlights', models.JSONField(blank=True, null=True)),
                ('social_links', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
