# Generated by Django 5.2.1 on 2025-05-10 15:07

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='highlights',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=core.storage.PublicAssetStorage(), upload_to='company_cover_images/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=core.storage.PublicAssetStorage(), upload_to='company_logos/'),
        ),
    ]
