# Generated by Django 5.2.1 on 2025-05-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
    ]
