# Generated by Django 5.2.1 on 2025-05-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDashboardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_filters', models.JSONField(blank=True, default=dict)),
                ('layout_preferences', models.JSONField(blank=True, default=dict)),
                ('email_notifications', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('new_company', 'New Company Registration'), ('new_job', 'New Job Posting'), ('reported_content', 'Reported Content'), ('verification_request', 'Verification Request')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('suspend', 'Suspend'), ('restore', 'Restore'), ('edit', 'Edit')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(default='StudentHunter', max_length=255)),
                ('supportEmail', models.EmailField(default='support@studenthunter.com', max_length=254)),
                ('maintenanceMode', models.BooleanField(default=False)),
                ('emailNotifications', models.BooleanField(default=True)),
                ('pushNotifications', models.BooleanField(default=False)),
                ('twoFactorAuth', models.BooleanField(default=False)),
                ('passwordExpiry', models.BooleanField(default=True)),
                ('smtpServer', models.CharField(default='smtp.example.com', max_length=255)),
                ('smtpPort', models.CharField(default='587', max_length=5)),
                ('smtpUsername', models.CharField(blank=True, max_length=255)),
                ('smtpPassword', models.CharField(blank=True, max_length=255)),
                ('smtpSecure', models.BooleanField(default=True)),
                ('logoUrl', models.CharField(default='/images/logo.svg', max_length=255)),
                ('faviconUrl', models.CharField(default='/favicon.ico', max_length=255)),
                ('primaryColor', models.CharField(default='#3B82F6', max_length=7)),
                ('primaryAccentColor', models.CharField(default='#2563EB', max_length=7)),
                ('secondaryColor', models.CharField(default='#10B981', max_length=7)),
                ('allowOpenRegistration', models.BooleanField(default=True)),
                ('requireEmailVerification', models.BooleanField(default=True)),
                ('allowStudentRegistration', models.BooleanField(default=True)),
                ('allowEmployerRegistration', models.BooleanField(default=True)),
                ('jobApprovalRequired', models.BooleanField(default=False)),
                ('companyVerificationRequired', models.BooleanField(default=True)),
                ('maxFileSizeInMb', models.PositiveIntegerField(default=5)),
                ('allowedFileTypes', models.JSONField(default=list)),
                ('cookieConsentRequired', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
